CREATE DATABASE chefai401;
USE chefai401;

CREATE TABLE ADMIN(
AEmail			VARCHAR(20)		NOT NULL,
APassword		VARCHAR(20)		NOT NULL,
PRIMARY KEY (AEmail)
);

CREATE TABLE REGISTEREDUSER(
MEmail			VARCHAR(20)		NOT NULL,
MPassword		VARCHAR(20)		NOT NULL,
DietaryRestrictions		VARCHAR(500)	,
PRIMARY KEY (MEmail)
);
