# Generated by Django 5.1.6 on 2025-03-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registereduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
