# Generated by Django 5.1.6 on 2025-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_registereduser_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereduser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="registereduser",
            name="password",
            field=models.CharField(
                default="defaultpassword123", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="auth_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="hashed_password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$f41duCnRR7TgMpVijK4YlR$S53FXaJh9AVSu4+hI+A2J49qSSGrGAiDL/RVTopemUs=",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="last_used_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="users_last_used", to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="users_saved", to="api.recipe"
            ),
        ),
    ]
