# Generated by Django 5.1.6 on 2025-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_registereduser_last_login_registereduser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="hashed_password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$A7d4PZAvs8dCZxBQVvSPXI$xT+DuUzvnK1p0NFn4UyBw/6J1dUg5PBRmpXh21HJ33w=",
                max_length=254,
            ),
        ),
    ]
