# Generated by Django 5.1.6 on 2025-03-18 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_registereduser_hashed_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registereduser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="registereduser",
            name="password",
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="auth_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="hashed_password",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="last_used_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="last_used_recipes", to="api.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="saved_recipes", to="api.recipe"
            ),
        ),
    ]
