# Generated by Django 5.1.6 on 2025-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_registereduser_auth_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registereduser",
            name="auth_token",
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
